# Generated by Django 4.2.4 on 2023-09-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_chatdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatdata',
            old_name='from_email',
            new_name='friend_email',
        ),
        migrations.RenameField(
            model_name='chatdata',
            old_name='from_message',
            new_name='friend_message',
        ),
        migrations.RenameField(
            model_name='chatdata',
            old_name='to_email',
            new_name='my_email',
        ),
        migrations.RenameField(
            model_name='chatdata',
            old_name='to_message',
            new_name='my_message',
        ),
    ]
